version: 2.1

parameters:
  trigger:
    type: boolean
    default: true
  engine:
    type: boolean
    default: false
  pwa:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: cimg/node:15.6.0

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  serverless: circleci/serverless-framework@1.0.1

jobs:
  trigger-workflows:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Set token
          command: |
            echo "export CIRCLE_USER_TOKEN=${CIRCLE_TOKEN}" >> $BASH_ENV
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/monorepo.sh && .circleci/monorepo.sh

  engine-deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - run:
          name: Deploy
          command: |
            cd apps/engine
            npm install
            serverless deploy

  pwa-build:
    executor: node
    steps:
      - checkout
  
  pwa-deploy:
    executor: node
    steps:
      - checkout

workflows:
  version: 2

  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows:
          filters:
              branches:
                only: master

  engine:
    when: << pipeline.parameters.engine >>
    jobs:
      - engine-deploy
  
  pwa:
    when: << pipeline.parameters.pwa >>
    jobs:
      - pwa-build
      - pwa-deploy:
          requires:
            - pwa-build