version: 2.1

parameters:
  trigger:
    type: boolean
    default: true
  engine:
    type: boolean
    default: false
  pwa:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: cimg/node:15.6.0

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  serverless: circleci/serverless-framework@1.0.1
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  trigger-workflows:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Set token
          command: |
            echo "export CIRCLE_USER_TOKEN=${CIRCLE_TOKEN}" >> $BASH_ENV
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/monorepo.sh && .circleci/monorepo.sh

  engine-deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - run:
          name: Deploy
          command: |
            cd apps/engine
            npm install
            serverless deploy

  pwa-deploy:
    executor: node
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy
          command: |
            cd apps/pwa
            npm install
            npm run build
      - aws-s3/sync:
          from: build
          to: 's3://sparticle-pwa-prod/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  version: 2

  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows:
          filters:
              branches:
                only: master

  engine:
    when: << pipeline.parameters.engine >>
    jobs:
      - engine-deploy
  
  pwa:
    when: << pipeline.parameters.pwa >>
    jobs:
      - pwa-deploy